costmap_filter_info_server:
  ros__parameters:
    use_sim_time: false
    type: 0
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0
filter_mask_server:
  ros__parameters:
    use_sim_time: false
    frame_id: "map"
    topic_name: "/keepout_filter_mask"
    yaml_filename: "/home/saikrishna/ros2_ws/src/agv_proto/maps/my_home_map_keepout2.yaml"
    #yaml_filename: "/home/saikrishna/ros2_ws/src/agv_proto/maps/my_home_map_keepout.yaml"
    #yaml_filename: "/home/saikrishna/ros2_ws/src/agv_proto/maps/remap_keepout.yaml"

