costmap_filter_info_server:
  ros__parameters:
    use_sim_time: false
    type: 1
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/filter_mask"
    base: 100.0
    multiplier: -1.0
filter_mask_server:
  ros__parameters:
    use_sim_time: false
    frame_id: "map"
    topic_name: "/filter_mask"
    yaml_filename: "/home/saikrishna/ros2_ws/src/agv_proto/maps/my_home_map_speedlimit.yaml"
    #yaml_filename: "/home/saikrishna/ros2_ws/src/agv_proto/maps/remap_speedlimit.yaml"
